name: Events with Filter
on: 
  push:
    branches:
      - main
      - 'main*'
    # paths-ignore:
    #   - '.github/workflows/*'
  workflow_dispatch:
  pull_request:
    types:
      - opened
    branches:
      - main    
jobs:
  My-job:
    runs-on: ubuntu-latest
    steps:
      - name: trigger-action
        run: echo ${{ toJson(github.event.pusher.name) }}
      - name: End-Workflow
        run: echo â€œExecution is completed"
       
